services:
  vectordb:
    image: ankane/pgvector:latest  # Postgres + pgvector baked in
    container_name: vectordb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      POSTGRES_DB: ai
    ports:
      - "5532:5432"
    volumes:
      - vectordb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ai"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  vectordb-data:
